/**
 * OpenSCAD template for case generation.
 * Ported from gen_scad.py CASE_TEMPLATE.
 */

export interface CaseTemplateParams {
  commonModule: string;
  width: number;
  height: number;
}

export function generateCaseTemplate(params: CaseTemplateParams): string {
  return `/**
 * This file is generated by layout file.
 * Do not edit this file directly.
 */

dimens = [${params.width}, ${params.height}, 10];
margin = 2;
with_nuts = true;

${params.commonModule}

difference() {
    outer_boundary(dimens);
    translate([margin, margin, margin]) {
        inner_boundary(dimens, margin);
    }
}
`;
}
