/**
 * OpenSCAD template for PCB generation.
 * Ported from gen_scad.py PCB_TEMPLATE.
 */

export interface PcbTemplateParams {
  commonModule: string;
  projection: string;
  placeholderSize: number;
  width: number;
  height: number;
  holes: string;
}

export function generatePcbTemplate(params: PcbTemplateParams): string {
  return `/**
 * This file is generated by layout file.
 * Do not edit this file directly.
 */

pcb_depth = 1.5;
hole_diameter_center = 4.1;
hole_diameter_pins = 3;
grid_size = 1.27;
offset = ${params.placeholderSize} / 2;
with_nuts = false;

${params.commonModule}

module switch_hole(z_angle=0) {
    translate([offset, offset, 0])
    rotate([0, 0, z_angle])
    union() {
        cylinder(h=pcb_depth, d=hole_diameter_center);

        translate([-grid_size*3, -grid_size*2, 0]) cylinder(h=pcb_depth, d=hole_diameter_pins);
        translate([grid_size*2, -grid_size*4, 0]) cylinder(h=pcb_depth, d=hole_diameter_pins);

        // diode pin: comment out, as this is ckbd v1 only
        //translate([7, hole_diameter_center/2, 0]) cylinder(h=pcb_depth, d=1.1);
    }
}

module pcb_mount_stabilizer_hole(z_angle, stabilizer_width_unit) {
    translate([offset, offset, 0])
    rotate([0, 0, z_angle])
    union() {
        translate([12, 8.5, 0]) union() {
            translate([-1.2, -0.1, 0]) cube([2.4, 2.4, pcb_depth]);
            cylinder(h=pcb_depth, d=3.4);
        }
        translate([12, -6.5, 0]) cylinder(h=pcb_depth, d=2.8);

        translate([-12, 8.5, 0]) union() {
            translate([-1.2, -0.1, 0]) cube([2.4, 2.4, pcb_depth]);
            cylinder(h=pcb_depth, d=3.4);
        }
        translate([-12, -6.5, 0]) cylinder(h=pcb_depth, d=2.8);
    }
}

module plate_mount_stabilizer_hole(z_angle, stabilizer_width_unit) {
    // nothing to do
}


margin = 2.5;

${params.projection}
rotate([180, 0, 0])
difference() {
    translate([margin, margin, 0]) {
        inner_boundary([${params.width}, ${params.height}, pcb_depth], margin);
    }
    ${params.holes}
}
`;
}
