/**
 * OpenSCAD template for plate generation.
 * Ported from gen_scad.py PLATE_TEMPLATE.
 */

export interface PlateTemplateParams {
  commonModule: string;
  projection: string;
  placeholderSize: number;
  width: number;
  height: number;
  holes: string;
}

export function generatePlateTemplate(params: PlateTemplateParams): string {
  return `/**
 * This file is generated by layout file.
 * Do not edit this file directly.
 */

plate_depth = 1.5;
switch_hole_size = 14;
offset = ${params.placeholderSize} / 2;
with_nuts = false;

${params.commonModule}

module switch_hole(z_angle=0) {
    translate([offset, offset, 0])
    rotate([0, 0, z_angle])
    translate([-switch_hole_size/2, -switch_hole_size/2, 0])
    cube([switch_hole_size, switch_hole_size, plate_depth]);
}

module pcb_mount_stabilizer_hole(z_angle, stabilizer_width_unit) {
    stabilizer_width = 9;  // width for one side (ie, left-side, right-side)
    stabilizer_height = 14;

    translate([offset, offset, 0])
    rotate([0, 0, z_angle])
    translate([-switch_hole_size/2, -switch_hole_size/2, 0])
    union() {
        translate([-stabilizer_width+0.1, 1, 0]) cube([stabilizer_width, stabilizer_height, plate_depth]);
        translate([switch_hole_size-0.1, 1, 0]) cube([stabilizer_width, stabilizer_height, plate_depth]);
    }
}

module plate_mount_stabilizer_hole(z_angle, stabilizer_width_unit) {
    stabilizer_width = 9;       // width for one side (ie, left-side, right-side)
    stabilizer_height = 12.5;   // switch_hole_size - 1.5;
    half_width = (${params.placeholderSize} * stabilizer_width_unit) / 2;
    padding = 3.1;

    translate([offset, offset, 0])  // move to center of switch
    rotate([0, 0, z_angle])         // rotate object
    union() {
        translate([-half_width+padding, -5.5, 0]) cube([stabilizer_width, stabilizer_height, plate_depth]);
        translate([half_width-stabilizer_width-padding, -5.5, 0]) cube([stabilizer_width, stabilizer_height, plate_depth]);
    }
}

${params.projection}
rotate([180, 0, 0])
difference() {
    outer_boundary([${params.width}, ${params.height}, plate_depth]);
    ${params.holes}
}
`;
}
